service: notes-app-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  environment:
    # atlas_connection_uri: mongodb://admin:admin@serverless-shard-00-00-ahez6.mongodb.net:27017,serverless-shard-00-01-ahez6.mongodb.net:27017,serverless-shard-00-02-ahez6.mongodb.net:27017/practiceserverless?ssl=true&replicaSet=serverless-shard-0&authSource=admin
    atlas_connection_uri: mongodb://root:root@cluster0-shard-00-00-b6g1j.mongodb.net:27017,cluster0-shard-00-01-b6g1j.mongodb.net:27017,cluster0-shard-00-02-b6g1j.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin


functions:
  create:
    handler: create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
  delete:
    handler: delete.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          request:
            parameters:
             paths:
               id: true
  fetch:
    handler: fetch.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          request:
            parameters:
             paths:
               id: true
  update:
    handler: update.main
    events:
      - http:
          path: notes
          method: post
          cors: true
