
service: first-example


provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    atlas_connection_uri: mongodb://root:root@cluster0-shard-00-00-b6g1j.mongodb.net:27017,cluster0-shard-00-01-b6g1j.mongodb.net:27017,cluster0-shard-00-02-b6g1j.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin



functions:
  hello:
    handler: Handler.hello
    events:
     - http:
         path: test
         method: get
  create:
    handler: Create.create
    events:
      - http:
          path: create_data
          method: post
  delete:
    handler: Delete.delete
    events:
      - http:
          path: notes_delete
          method: get
  fetch:
    handler: Fetch.fetch
    events:
      - http:
          path: notes_fetch/{id}
          method: get
  update:
    handler: Update.update
    events:
      - http:
          path: notes_update
          method: post

